### ISSUE TITLE
Not compatible with DNN 7.4.1

### ISSUE THREAD

**Issue by billbayjr** [DNNCommunity/DNN.ActiveDirectory#1]
1. Overwrites Firstname with Username 
2. Overwrites Lastname with Domainname 
3. Removes email 
   -- All on each and every login.

**Comment by otg2** [comment]
How long until it is fixed? I want to try this but not sure I'll do it if it breaks everything.

**Comment by EPTamminga** [comment]
It will be fixed if there is someone who is willing to provide the codefix. DNNPlatform is Open Source, which can only exist if people are willing to contribute. Getting your copy of the source is easy here, just fork and clone.
Can you provide the codefix?

**Comment by otg2** [comment]
That's what I did. I got the source code and I made a copy of my project to see what happens. So if I manage to bypass this I will of course contribute.

(this was mere a question if OP or someone else was already working on it, no hostility intended)

**Comment by EPTamminga** [comment]
Tnx for your efforts. Yiu van assign yourself to this issue, so that people know you are on it...

**Comment by mortezakermani** [comment]
Did anybody make this module compatible with DNN 7.4.1 by any chance?

**Comment by otg2** [comment]
I did look into it - I did not encounter these problems at all. But I'm having another issue, for some reason it only works when I'm running the website as localhost. When I try to access with the AD on the server where the site is hosted, it only says the the username might be wrong and/or the password is incorrect.

So yes it is compatible with 7.4.1 but it is having some troubles. I'm going to uninstall the extension and re-install it via server side, see it if has anything to do with portal settings or something. But it shouldn't right?

**Comment by EPTamminga** [comment]
I shouldn't.

**Comment by sunilmittal22** [comment]
Hi , the Provider is working for me  for DNN version # 07.04.02 (216).  I made some minor code changes replaced the deprecated functions.  I may have to do some code cleanup before I can do a pull request with proposed changes.

**Comment by EPTamminga** [comment]
@sunilmittal22 Great news! Thank you for your feedback and PR's are most welcome!

BTW Can I ask you to do some coordination for the module? Create a new version and make it available here?

**Comment by sunilmittal22** [comment]
Sure I will do this.

**Comment by efficiondave** [comment]
Any update on this? I upgraded a site to DNN 7.4.2 without checking on compatibility and now things are messed up. Would rather not roll back if it can be avoided.

**Comment by sawest** [comment]
If you are still having an issue, try downloading the new version and see if you continue to have issues.  Please report any issues you experience.

**Comment by sawest** [comment]
I am closing this issue to lack of activity.  I have tested the extension all the way to DNN 9 and it works.
