### ISSUE TITLE
Active Directory creating too may redirects on DNN8

### ISSUE THREAD

**Issue by MatthewKatakam** [DNNCommunity/DNN.ActiveDirectory#10]
We just upgraded http://melbournecatholic.org.au/ to DNN8 and Installed AD module after that we realized that we no longer able to post stories to Facebook and the RSS feeds are creating problems due to too may redirects on the pages. After I switched off the AD Authentication the website works fine... This module has been a lifesaver for me and I appreciate all the work you guys put in.

Cheers
Matthew

**Comment by sawest** [comment]
@MatthewKatakam which version of the AD module did you install?  I am not aware that the AD module is related in anyway to the Facebook or RSS feed modules. 

Can you give me exact steps to replicate the issue?

**Comment by sawest** [comment]
Closing issue due to lack of response.

**Comment by ghkamfung** [comment]
We are using DNN9 and see the same problem.
It keep redirect to ?portal=0

**Comment by mortezakermani** [comment]
I'm having the same issue in DNN 9.2.0.

there are a lot of ?portal=0 parameters in url and site breaks

The last version of Active Directory worked for me is 05.00.02. no other versions work correctly.

**Comment by ghkamfung** [comment]
Something like this:
http://10.145.2.77/?portalid=0?portalid=0?portalid=0?portalid=0?portalid=0?portalid=0?portalid=0?portalid=0?portalid=0?portalid=0?portalid=0?portalid=0?portalid=0?portalid=0?portalid=0?portalid=0?portalid=0?portalid=0?portalid=0?portalid=0

**Comment by valadas** [comment]
This repository could use a maintainer that is familiar with ActiveDirectory if anyone has the knowlege to tackle this, please let yourself heard.
