### ISSUE TITLE
Pre-Existing AD account cannot login 

### ISSUE THREAD

**Issue by rbeghin** [DNNCommunity/DNN.ActiveDirectory#11]
I have been using previous versions DNN Active Directory for many years and have been very pleased with it. I am working on deploying version 6.0.0 on DNN 9.0.2 installed on Windows Server 2008 R2. 

I was able to successfully install it and get it to authenticate Active Directory users: user1, user2, user3. I was able to login those accounts using either the Default Domain and/or domain\username. I did not try SSO.

As a part of testing, I deleted the portal and then created a new portal with a completely new name and URL. I've configured DNN Active Directory for the new portal

Problem: I cannot login user1, user2 or user3 to the new portal (tried every login format possible). However, I can login new users (user4, user5, etc.) without any problem.

Thank you in advance for any assistance.

**Comment by rbeghin** [comment]
Update Workaround: I was able to get the users to be able to login by deleting their SQL entries under dbo.users then dbo.aspnet_Membership and finally dbo.aspnet_Users and then restarting IIS.

**Comment by sawest** [comment]
Users in multiple portals was fixed in 6.1.2.  I believe that this issue is corrected a side effect.  If anyone can test and confirm that would be great!

**Comment by rbeghin** [comment]
sorry for the late reply. unfortunately it is not possible for me to test this as it would mean that the site I've got in internal dev would need to be deleted and it's just about ready to go into production. thank you for the work you've put into the module. hopefully the problem has been resolved.
