### ISSUE TITLE
RFE: Set Keyboard Enter to elicit Login function

### ISSUE THREAD

**Issue by rbeghin** [DNNCommunity/DNN.ActiveDirectory#13]
More of a convenience thing.... It would be nice if after entering credentials one could just hit enter rather than having to click the Login button, especially since the Login button is to the left of the Username/Password column. Thanks

**Comment by sawest** [comment]
#14 
Pull request has been made, new release uploaded.  Update to 6.0.2 to see if issue is resolved.

**Comment by sawest** [comment]
@rbeghin any feedback on this?  Wanted to wait for you verification before closing issue.

**Comment by rbeghin** [comment]
sorry I've been away from this project. I'll send an update an a couple of days or so. Thanks,

**Comment by rbeghin** [comment]
Works great. You can just hit Enter after putting in credentials.

However, there might be a problem with the installer package. I installed the package assuming that it was an upgrade. It did not upgrade and instead 6.0.0 was still there with an option to delete. Version 6.0.2 appears as another extension BUT it does not have a delete option. I thought maybe there was a problem with the extension installation so I deleted 6.0.0 and then I re-installed 6.0.2 and now I have two versions of 6.0.2 showing as installed. But that said the module is authenticating AD.
