### ISSUE TITLE
No Auto Login in DNN 9

### ISSUE THREAD

**Issue by thosalbert** [DNNCommunity/DNN.ActiveDirectory#16]
I am trying to get this extension to work. I am running DNN9, and can get automatic Windows Log in by browsing to the WindowsSignIn.aspx page, but cant seem to get auto log in to work. 

Has this been tested in DNN 9?

I've got a thread going here as well (read towards the end):

http://www.dnnsoftware.com/forums/forumid/199/threadid/538310/scope/posts

Thanks
Tom

**Comment by sawest** [comment]
I have not tested the auto login feature for DNN 9.  Please post your findings.  I do not use the auto login feature so anything you can provide would be helpful.

**Comment by thosalbert** [comment]
Thanks for your reply. When I browse to the website URL, it doesn't automatically re-direct to the Windows sign-in page (WindowsSignin.aspx). If I browse directly to the Windows sign-in page (while logged in to the AD network), I do get logged in. I've tried this in two DNN instances (running 9.1.1) with the same results. 
Do you know what else I can do to try and get the auto log in working?

**Comment by sawest** [comment]
Version 6 of this extension automatically disables that feature.  To enable, go to the web.config of the DNN site and look for  <windowsAuthentication enabled="false" />
Set that to true and save.

Restart IIS, and browse to your site.  Please post your results.

**Comment by sawest** [comment]
Sorry didnt post the code.  Look for this in the web.config file ` <windowsAuthentication enabled="false" />`

**Comment by thosalbert** [comment]
Thanks for the info. 
I just tried that, and so far am getting the same results. On one of the sites, that setting was "false", so I set it to "true". The other was already "true". Then I did an IIS reset on both servers and restarted the websites. The behavior looks the same as before. 

Also (in both cases), there is also a web.config inside the /DesktopModules/AuthenticationServices/ActiveDirectory/ folder., which has a configuration tag  for the WindowsSignin.aspx page - this is also set to windowsAuthetication enabled="true" and anonymousAuthentication enables="false".

Anything else I should look for to try to get this feature working? 

Thanks
Tom

**Comment by thosalbert** [comment]
Is there anything else I can look into in my DNN installations to try to fix the auto log in feature?

Thanks

Tom

**Comment by sawest** [comment]
I am not able to find anything else at the moment.  I will keep looking as I have time and post any findings here.

**Comment by thosalbert** [comment]
Thanks. I appreciate it.

Tom

**Comment by Audun1555** [comment]
Try setting 1.0.0.1-255.255.255.255 as autologon ip range ... (and clear cache both in browser and in DNN)
Autologin does not seem to work in DNN 9 without a valid range configured (at least from my testing)

**Comment by sawest** [comment]
Thanks for the information @Audun1555!  I will be looking into the issue you posted.

**Comment by thosalbert** [comment]
Thanks. Using that auto login range fixed it for me. 

However, recently, auto login and registration began to fail intermittently. I have had a few users (on the AD network) browse to the site, but not get automatic registration (which was working great in the past) 

I'm using version 6.0.2... In my settings I'm getting:

----------
Accessing Global Catalog: OK
Checking Root Domain: FAIL
Accessing LDAP: OK
Find all domains in network:  Could not access LDAP to obtain domains info
--------------------------

This was working fine before. I don't know what changed. It looks like the Root Domain setting might need to change. Any tips?

Thanks
Tom

**Comment by thosalbert** [comment]
OK. I got the settings to work (and turn Green) by putting username domain in lowercase and re-entering the password. 

But Auto login is still intermittent. It's not working in IE, but works OK in Mozilla and Chrome. 

Any ideas?

Thanks

Tom

**Comment by sawest** [comment]
How do you have autologin setup?  Also, are you using IE or Edge?

**Comment by thosalbert** [comment]
Thanks for your reply , and sorry for the delay in my response. 

I've managed to get AD authentication working. (with a few exceptions), it's working quite consistently (using IE, edge, Firefox and Chrome). 

The auto log-in range setting (1.0.0.1-255.255.255.255) fixed it for me. 

Thanks again! Very appreciated.

Tom

**Comment by valadas** [comment]
So if I understand this correctly, it does work with Dnn 9.1.1 but would need better documentation correct?

Can one of you test and let me know if it works in Dnn 9.2, I am in the process of trying to revive all these old community modules/providers and I want to check on Dnn 9.2 compatibility for all of them, but I am not familiar with Active directory.

Thanks.

**Comment by sawest** [comment]
This issue was addressed in 6.1.2 and documentation was updated in the Wiki.
