### ISSUE TITLE
Do enabling windows auth in IIS for a website is required to make AD authentication work?

### ISSUE THREAD

**Issue by roman-yagodin** [DNNCommunity/DNN.ActiveDirectory#18]

**Comment by sawest** [comment]
Not sure if this is an issue or just a question?  Yes you must enable windows authentication for the website if you want to use this extension.

**Comment by roman-yagodin** [comment]
It's a question, thanks.

**Comment by roman-yagodin** [comment]
I finally managed to make it work! 😌 I thought that **Do Not Automatically Create Users?** flag is about creating accounts in AD, but it is about creating corresponding accounts in DNN.

Enabling windows authentication in IIS is not required - at least if you do not need it to be transparent, I suppose.

Thanks for your work, @sawest! 👍
