### ISSUE TITLE
AD Module Overrides the password of local DNN account

### ISSUE THREAD

**Issue by ainsofs** [DNNCommunity/DNN.ActiveDirectory#2]
When loading up a site using this module it redirects me to a standard DNN login screen. I have set the default tab to be the Active Directory login (by modifying the desktopmodules/admin/Authentication/login.ascx file). I select the DNN login tab to login in with a DNN account. When I do this, the module overrides that accounts password with the hashed Active directory password.

I have to log in as host and reset the passwords back each time this happens.

I can avoid this when I remove the redirect Query Strings (eg Login.aspx?ReturnUrl=%2fDesktopModules%2fAuthenticationServices%2fActiveDirectory%2fWindowsSignin.aspx%3fportalid%3d0&portalid=0) and just use Login.aspx.

I am using DNN 7.4.1 and AD Module 5.0.6

OS: Microsoft Windows NT 6.1.7601 Service Pack 1
IIS: Microsoft-IIS/7.5
.Net Framework: 4.0.30319.1

Appreciate any help.

Cheers,

**Comment by EPTamminga** [comment]
Can you look a the code and find the problem? The source is available as a fork/clone

**Comment by ainsofsoo** [comment]
Can you post some instructions on the readme file on how to set this project up on vs2013? I am having problem setting it on with DNN 7

**Comment by EPTamminga** [comment]
The normal procedure is to have a clean fresh DNN installatione and install the source pack of the module as a normal module. Then open the VS solution and correct any references if needed until you can build the solution.
I have not tried this for this module myself, but that is the normale procedure.

**Comment by ainsofsoo** [comment]
Thanks I will try this in DNN 6 as it seems DNN 7 is missing the

**Comment by ainsofsoo** [comment]
*Update*

I've found a work around for now. I've removed the custom code I added to the Login.ascx file and used the Site Settings > User Account Settings > Login Settings and set the default authentication provider to AD as noted here https://dnntracker.atlassian.net/browse/DNN-2996

I will take a look at the code when I can. Thanks for the instructions.

**Comment by sawest** [comment]
version 6.0.4 is now available.  If this issue crops up again please reopen the issue.
