### ISSUE TITLE
Error when upgrading to DNN 9.1.1

### ISSUE THREAD

**Issue by muddeatr** [DNNCommunity/DNN.ActiveDirectory#32]
Part of the testing with this module has been working great with the latest updates (v. 6.0.6) !!

Now I'm updating my DNN test site from 8.0.3 to 9.1.1 and during the upgrade I got an error:
**Installing Package File DNN_DNN_ActiveDirectoryAuthentication_05.00.03_Install:  Error!**

I will be testing the next few days but just wanted to give you this as a heads up. If you know where I can look to get more info on this error for you just let me know.

**Comment by muddeatr** [comment]
@sawest I think this install package needs to be cleaned up. I don't know enough about the whole install process but I believe I am getting that error because there is a file called
"DNN_DNN_ActiveDirectoryAuthentication.dnn" in the ActiveDirectory folder but the contents of that file says version 5.0.3 and a lot of the XML format has been escaped.

**Comment by sawest** [comment]
@muddeatr do you experience anything similar to issue #33 along with this?

**Comment by muddeatr** [comment]
I didn't really have any problems that I am aware of. I installed the 6.0.6 over top of 5.0.3 and been testing away. Everything seems to work great 😊 I then went to install DNN 9.1.1 for testing (although I'm waiting for 9.2) and I got that error message while installing 9.1.1

Installing Package File DNN_DNN_ActiveDirectoryAuthentication_05.00.03_Install: Error!

________________________________

**Comment by muddeatr** [comment]
@sawest I just double checked. I am only showing 1 version (6.0.6) installed. So no I did not have that problem similar to #33.

**Comment by muddeatr** [comment]
@sawest I may have a lead for you and since I'm not 100% on install/developing DNN modules you can let me know. 

On my current site that has the AD 6.0.6 installed I found this in the DNN install folder at the root. DNN_DNN_ActiveDirectoryAuthentication_05.00.03_Install.zip

Should that zip file even be there? I'm not sure why it's there.
Should the install of 6.0.6 delete that then replace it?

**Comment by sawest** [comment]
I have never seen a zip file named DNN_DNN_ActiveDirectoryAuthentication_05.00.03_Install.zip before.  I have searched all the install packages and have not found that file.  I wonder if the DNN upgrade created and placed it there to install after the upgrade and failed.

I am trying to do some research about it.  If this is the case, I wonder why DNN 9.1 thought it needed AD 5.0.3 installed?

**Comment by sawest** [comment]
Also, are there any even logs you could post?

**Comment by sawest** [comment]
It appears that cleaning the install folder is good practice before an upgrade.  I am not sure where that zip file came from but deleting it from the install folder should allow you to upgrade.

Referenced by Joe Brinkman's comment here: [http://www.dnnsoftware.com/answers/upgrade-from-705-to-71-install-error](url)

**Comment by muddeatr** [comment]
I tried a new approach last Friday and didn't get a chance to post a follow up for you. I did delete that AD zipfile from the DNN install directory and upgraded to DNN 9.1.1 with no issues.

**Comment by sawest** [comment]
Groovy @muddeatr.  Since this can happen with any module (isn't exclusive to this particular one) I would like to close this issue.  I think its more of a DNN upgrade procedure issue.  In the case someone has this problem in the future the fix is documented here for reference.

Appreciate all the help!

**Comment by muddeatr** [comment]
Haha! I have a second authentication system that accesses our employee database for non windows users and for some reason that system had an install package under DNN too. Yeah I'd like to know what, and why those packages were created in the install.
