### ISSUE TITLE
How to access AD User profile variables using javascript

### ISSUE THREAD

**Issue by thosalbert** [DNNCommunity/DNN.ActiveDirectory#35]
Hi, 

Once you have a user authenticated, is it possible to access user profile information (User name, email, phone, etc) by using javascript? If so, how would you call the info?

Thanks

Tom

**Comment by sawest** [comment]
There is not any user profile info stored client side that I am aware of.  One option is to use javascript to do an AJAX call back to the server to retrieve the info needed.  But a more popular option would be to use server-side block tags as discussed here: [http://www.dnnsoftware.com/forums/threadid/489523/scope/posts/get-login-user-userid-in-javascript](http://www.dnnsoftware.com/forums/threadid/489523/scope/posts/get-login-user-userid-in-javascript).

Those block tags can be used in very creative ways.  You could simply add them to a hidden input box on a page for user later in your flow.  I think that article is using them straight in the javascript.
