### ISSUE TITLE
DNN User Logoff with WinLogin status

### ISSUE THREAD

**Issue by ryancyq** [DNNCommunity/DNN.ActiveDirectory#38]
Noted that when a user clicked logout from account menu (beside username at the top right corner), `Login.aspx` will be shown to user, the authentication status still remains at **WinLogon**.

Just want to check if this behaviour is by design.

**Comment by sawest** [comment]
I think this makes sense.  Admins can configure logout redirect in the Admin settings of the portal if it needs to go somewhere else.  If that is not set, we need a default page to go somewhere so Login.aspx is as good as any I think.
