### ISSUE TITLE
Getting "password incorrect" errors for every (successful) AD Login 

### ISSUE THREAD

**Issue by thosalbert** [DNNCommunity/DNN.ActiveDirectory#39]
Hi, I have AD authentication with auto login working on an intranet website. The auto log in appears to be working fine, but when I look at the admin logs, I see that for every "Login Success" there are three General Exceptions generated at the same time. The URL is the WindowsSignin.aspx page, and the error message is: "The username or password is incorrect". Any idea what is going on to cause this? 
Again, the log in seems to work fine (the user doesn't see the error), but the errors show in the Admin log. So there are a huge amount of errors there. 

(This is not to be confused with my other question about using AD Authentication on multiple portals, which I am trying to get to work on a different test server) .

Thanks for any insight into this.

Tom

Here's the error:
**AbsoluteURL:**/DesktopModules/AuthenticationServices/ActiveDirectory/WindowsSignin.aspx
**DefaultDataProvider:**DotNetNuke.Data.SqlDataProvider, DotNetNuke
**ExceptionGUID:**f617a3e0-14c9-40f9-85b2-8256fb0a6b3d
**AssemblyVersion:**
**PortalId:**-1
**UserId:**-1
**TabId:**-1
**RawUrl:
Referrer:
UserAgent:**
**ExceptionHash:**yTkxsR/IDapJeM6viuW1ux625Es=
**Message:**The user name or password is incorrect.
**StackTrace:**
at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail) at System.DirectoryServices.DirectoryEntry.Bind() at System.DirectoryServices.DirectoryEntry.get_AdsObject() at System.DirectoryServices.PropertyValueCollection.PopulateList() at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName) at System.DirectoryServices.PropertyCollection.get_Item(String propertyName) at DotNetNuke.Authentication.ActiveDirectory.ADSI.Domain.PopulateInfo() at DotNetNuke.Authentication.ActiveDirectory.ADSI.Domain..ctor(String Path, String UserName, String Password, AuthenticationTypes AuthenticationType) at DotNetNuke.Authentication.ActiveDirectory.ADSI.Domain.GetDomain(String Path, String UserName, String Password, AuthenticationTypes AuthenticationType) at DotNetNuke.Authentication.ActiveDirectory.ADSI.Utilities.GetRootDomain()
**InnerMessage:
InnerStackTrace:**
**Source:**System.DirectoryServices
**FileName:**
**FileLineNumber:**0
**FileColumnNumber:**0
**Method:**
**Server Name:** SCZAS51

**Comment by sawest** [comment]
Please install v6.00.08 to see if this is fixed.  Please report your results here.  Thanks!

**Comment by thosalbert** [comment]
OK, I installed 6.00.08 on the test server, but it looks like it's behaving similar to before, in terms of getting AD authentication to work on multiple portals. I had the same result pattern, in which it works fine when just one portal is enabled, but when I enable the second portal, I can no longer access the windowssignin.aspx page. This time I actually got into a state where (for both portals) I couldn't even browse to the login page directly on either portal (it would always try to go to the windows signin page, and then fail to authenticate). In that case, I was able to get back to the login page by commenting out the following line from the web.config:


Then, I could log back in as host and disable AD authentication, uncomment out the above line again, restart, and start over. I could never get it to work in multiple portals. I can only get it to work in the first portal (0) when the other portal (2) is not enabled for AD authentication. When I tried the other way around (portal 2 enabled, and portal 0 disabled), it also doesn't work. Only works on the first portal (0), when the second is disabled.

I appreciate your efforts! I will try this version on the live site later, to see whether it fixed the other (errors on login) problem, 

It's of course possible (probable?) there is something wrong with how I'm doing this... I've checked the permissions for the windows signin page and unlocked the sections for anonymous and windows authentication in IIS.
I check the site web.config and the web.config inside DesktopModules/AuthenticationServices/ActiveDirectory, to make sure that windowsAuthentication enabled is set to "true" . 

Anything about the AD Authentication Site Settings I might need to know? Maybe I should use a different user/password combo for the second portal? What about the "Default Authentication Provider" inside Security? 

Thanks again for your help on this. I remember you said you have it working on multiple portals, but without auto log-in. Does that mean unchecking "Do Not Automatically Create Users?" How does that work? Can you have the same user inside multiple portals? 

Thanks again

Tom

**Comment by thosalbert** [comment]
Hi again, I installed version 6.00.08 , and I'm still getting the same problem, three errors (sometimes more) for every successful log-in. So, no luck so far. 

Thanks for your efforts. I appreciate it!
Tom

**Comment by sawest** [comment]
Sorry, been wrapped up at work.  Havent had a change to dig into but will as soon as I get free time.

**Comment by thosalbert** [comment]
Thanks for the response! This isn't causing me real trouble beyond filling up the logs. 

I'm still curious about the multi portal issue as well (my other thread here)  - I'm going to refresh our test sever and try that again from scratch. 

I appreciate your effort, whenever you have time. Thanks again

**Comment by sawest** [comment]
I made some changes to password randomization in release 6.1.2.  Please try this version at your earliest convenience as I believe it will correct this issue.
