### ISSUE TITLE
Mike Volodarsky's FormsAuthenticationModule (MVolo.FormsAuthenticationModule.dll)

### ISSUE THREAD

**Issue by Raeoomus** [DNNCommunity/DNN.ActiveDirectory#4]
Hi, 

I am trying to develop an AD authentication system for our intranet which we want to use DNN (preferably 8 but can settle for 7.3 or 7.4).

I prefer a living maintained module but if I have to take it in-house and keep it alive myself, that's fine.

Other than paid products, this is the only one I can find. However, I cannot find where the project comes with a pre-built, read-to-install zip. Okay, no big deal. But it took a bit of effort to get the this project's source code to even load in VS 2013 (no documentation). 

I've finally been able to load the projects and some tinkering has almost made it build. Unfortunately my latest roadblock is Mvolo.FormsAuthenticationModule.dll. This is not included in the download. Nor can I find it on the web as the [links are dead](http://mvolo.com/iis-70-twolevel-authentication-with-forms-authentication-and-windows-authentication/). 

Where can I get this module? Do I need this module? Is this no longer needed? There was no mention of this whatsoever in the [Prerequisits](https://github.com/DNNCommunity/DNN.ActiveDirectory/wiki#prerequisites).

If possible, I would prefer the source code for it. My goal is to convert all this to C# and perhaps a single module.

Thanks

**Comment by sawest** [comment]
The install package for DNN Auth AD is found here: http://dnnauthad.codeplex.com/

I am currently using it with DNN 8 with out issue.

**Comment by Raeoomus** [comment]
Thanks. I've installed it without any warnings on a brand new install of DNN 8. 

However, the [posted configuration](https://github.com/DNNCommunity/DNN.ActiveDirectory/wiki#part-3-configuration) tells me to find advanced setting on the Extensions page, Authentication Systems, edit DNN_ActiveDirectoryAuthentication. Editing that module there does not have anything that I can fill out for domain settings. The module does not appear in the modules list above so I cannot edit it there either. 

I do not see it listed in Site Settings|Login Settings>Default Authentication Provider. I tried creating a custom login page to drop the control on but cannot find it in the list of modules. Uninstall/Reinstall did not change anything.

Hosted on Server 2012, IIS 8.

What did I miss?

**Comment by sawest** [comment]
You will need to go to the Admin>Extensions page to edit the settings. Do not go to the Host>Extensions page.  Under Admin>Extensions, go to the Authentication Systems panel to edit the domain settings.  You will need to enable the module here as well.

**Comment by Raeoomus** [comment]
Completely removed DNN site and database. Reinstalled DNN 8. Same result.
Tried on install of DNN 7.4. Same result.

Why am I not seeing the AD configuration? Just the following:

Authentication Settings
-      Authentication Type
-      Login Control Source
-      Logoff Control Source
-      Settings Control Source
-      Enabled?

Package Settings
-      [standard stuff]

Any ideas? The module does not list in the regular modules section of DNN7 either.
@sawest  was your DNN8 an upgrade or clean install?

**Comment by Raeoomus** [comment]
Never mind. Completely my fault. Was looking at Host Extensions, not Admin. :-/
