### ISSUE TITLE
DNN 7.2.1 not working with DNN Active Directory 6.00.06

### ISSUE THREAD

**Issue by RobbieBrandrick** [DNNCommunity/DNN.ActiveDirectory#43]
I am trying to get ad auto sign in to work for our DNN intranet site. We are running DNN 7.2.1. Currently we have been using DNN Active Directory version 5.06, but I can't seem to get auto sign in to work after carefully following the instructions on the wiki and experimenting with different settings-. When I install the latest version of DNN Active Directory (i.e., 6.00.06) I receive the following error message after the installation: "Could not load type 'DotNetNuke.Entities.Users.IUserController' from assembly 'DotNetNuke, Version=7.2.1.367, Culture=neutral, PublicKeyToken=null'." I have also tried installing DNN Active Directory 6.00.00, but I receive the same error. Any assistance would be appreciated. Thanks.

**Comment by RobbieBrandrick** [comment]
The issue I am having with DNN 7.2.1 and AD 5.06 is when I go to the web site I am being prompted for a username and a password in a browser dialog box (basic auth). None of the ad admin accounts seems to work for a successful login. When I click cancel on the dialog then I receive a 401.1 Unauthorized. Here some information from that screen:

'Requested URL': http://<address>/DesktopModules/AuthenticationServices/ActiveDirectory/WindowsSignin.aspx?portalid=0
Physical Path: \DesktopModules\AuthenticationServices\ActiveDirectory\WindowsSignin.aspx
Module: WindowsAuthenticationModule
Error Code: 0xc000006d

**Comment by sawest** [comment]
DNN doesn't cause the dialog box.  That usually is on the web server level.  Perhaps permissions on the windowssignin.aspx file? 

I am busy with my "real" job right now but will get back to this project soon.  Hopefully I can give a more verbose answer at that time.

**Comment by RobbieBrandrick** [comment]
Thanks for the response. I have looked into permissions in IIS, and NTFS for the WindowsSignIn.aspx file, and made quite a few tweeks to no avail. I have had a couple other sets of eyes on this problem as well (including a network administrator) but they were not able to find the issue. I even installed DNN 9 with the latest AD module, but I am getting the same issue. Not sure what else I can try... If it helps I am running windows 7 with IIS version 7.5. I have not tried this on our servers because I wanted to have it work locally first.

**Comment by sawest** [comment]
Look in your web.config file and see if you can find this portion.  Should be at the bottom:
` <location path="DesktopModules/AuthenticationServices/ActiveDirectory/WindowsSignin.aspx">
    
    <formsAuthenticationWrapper enabled="false" />
    <system.webServer>
      <security>
        
        <authentication>
          <windowsAuthentication enabled="true" />
          <anonymousAuthentication enabled="false" />
        </authentication>
      </security>
    </system.webServer>
  </location>`

Does it match mine?

**Comment by RobbieBrandrick** [comment]
Yes. It appears that yours and mine are a match. Here is mine directly from the web.config:

`  <location path="DesktopModules/AuthenticationServices/ActiveDirectory/WindowsSignin.aspx">
    
    <formsAuthenticationWrapper enabled="false" />
    <system.webServer>
      <security>
        
        <authentication>
          <windowsAuthentication enabled="true" />
          <anonymousAuthentication enabled="false" />
        </authentication>
      </security>
    </system.webServer>
  </location>`

Under System.web I also have this too (mentioning as I am unsure if that is correct, although, I have tried all variations that I can come up with):

`    
    <authentication mode="Forms">
      <forms name=".DOTNETNUKE" protection="All" timeout="720" cookieless="UseCookies" />
    </authentication>
    `

**Comment by RobbieBrandrick** [comment]
Should there be a code behind for the WindowsSignin.aspx in my project?

**Comment by RobbieBrandrick** [comment]
Interesting, because I don't see the code behind in the .zip file (i.e., ActiveDirectory_05.00.06_Install.zip). I downloaded this from here: https://github.com/DNNCommunity/DNN.ActiveDirectory/releases

**Comment by sawest** [comment]
The install package doesnt have source code.  You need to download the source package.

**Comment by RobbieBrandrick** [comment]
Just to confirm though, do I need the code behind to make the install package work?

**Comment by sawest** [comment]
No you do not need the code behind for installation.  All code behind compiles into a single dll file that is included in the install package.

**Comment by sawest** [comment]
The wiki has been updated to explain the problem with local server auto login.

**Comment by RobbieBrandrick** [comment]
> The wiki has been updated to explain the problem with local server auto login.

FYI... I see you updated the wiki, but it doesn't contain a hyperlink to the article. I think the wiki is missing many hyperlinks. Could you just specify the full URL since hyperlinking isn't working?

**Comment by RobbieBrandrick** [comment]
> I was able to spend some time working on the autologin feature. I have found a major problem on the Microsoft side. If you are browsing to a website on the local machine using a hostname other than the actual hostname then you will get the 401 and/or pop up box. Here is the workaround for this situation: [https://support.microsoft.com/en-us/help/896861/you-receive-error-401-1-when-you-browse-a-web-site-that-uses-integrate](url)
> 
> This problem should not present if you browse to a the site not on your local machine. Please report any results.

This fixed the problem! Thank you.

**Comment by vamsisagi** [comment]
I am getting the same issue. Can you please explain how you resolved this.

**Comment by sawest** [comment]
I have updated the wiki.  Not sure why the link wasnt working.

@vamsisagi the link above and in the wiki explain how to work around the issu

**Comment by vamsisagi** [comment]
@sawest I followed the steps and it worked in my local machine. When I am trying to do the same in production but didn't work. In production, I tried both methods that you have suggested.
Is there anything that I need to try.

**Comment by sawest** [comment]
Unfortunately if you indeed are experiencing the problem listed in this issue, I am rather limited on helping as it is outside the scope of this module.  The link above is about all I can do to help.  Post any fixes/research you can to help others.  If I run across any other fixes for this I will post as well.
