### ISSUE TITLE
Need an updated version for DNN 8

### ISSUE THREAD

**Issue by bhattjidotcom** [DNNCommunity/DNN.ActiveDirectory#5]
Hi

This is an excellent module. I tried it on DNN 8, it worked on Chrome ok. It did not worked on IE though, I tried several things after googling, none of them worked, and finally, it stopped working on chrome too :(

Can we have a robust module, that works with DNN 8?

**Comment by morgenweck** [comment]
Will this every work with 8.+?

**Comment by mwiikned** [comment]
I recently set up this module on DNN 8 and confirmed that it works in Chrome and IE. What issues have you come across that are causing this module to not work?

**Comment by sorosliu** [comment]
@mwiikned Hi, I tried this module on Windows 2012. When I tried to change the settings on IIS, it poped up error. I think the syntax in web.config might be different.

**Comment by sawest** [comment]
You might try the new version.  Usually the error you experience is due to windows authentication being enabled by default.  You have to make a web config change.  The new version has this disabled by default instead.

**Comment by bhattjidotcom** [comment]
Hi

Now that the DNN9, introduces, once again breaking changes, will this work on DNN9+ ?

**Comment by sawest** [comment]
I have not tested it on DNN 9 as of yet but I anticipate no problems.

**Comment by sawest** [comment]
I have tested this on DNN 9 as well without any issues.
