### ISSUE TITLE
Request more event logs at various points of failure

### ISSUE THREAD

**Issue by zhenlee** [DNNCommunity/DNN.ActiveDirectory#54]
In one of our environments (UAT to be specific), windows login with auto create feature ON failed to create a user in user table. It's extremely difficult for troubleshooting because of lack of logging at various points.

I recommend adding DEBUG and ERROR messages at following points (far from exhaustive)
- DEBUG message should be turn on and off
- ADSIProiver GetUser method, log debug message before returning objAuthUser, the debug message should print out entire objAuthUser object
- AuthenticationController CreateUser, log debug message before the method return, the debug message should log createStatus 
- AuthenticationController AuthenticationLogon, the else part of the "If Not (objReturnUser Is Nothing)" should log ERROR message, indicating failure in AuthenticateUser
- In the same method, before HttpContext redirects, log DEBUG message of strUrl.

This is a complex module with so much going on, the different levels of logging are needed extensively for the module. And a portal setting should be added to toggle on and off of DEBUG messages. 

Thank you very much! And hope to hear more on this.

**Comment by sawest** [comment]
These new logs were added in version 7.00.00.
