### ISSUE TITLE
DNN 9.2.2 not working with DNN.ActiveDirectory-6.01.02

### ISSUE THREAD

**Issue by giangpv171** [DNNCommunity/DNN.ActiveDirectory#57]
Hi,

I got the issue "error while processing windows authentication check your IIS settings. DesktopModule/AuthenticationService/ActiveDirectory/Windows Signin.aspx should NOT allow anonymous access" when I accessed to my DNN site using Windows Authentication(Single Sign On).

Here what i have done:
1. I upgraded DNN version from 9.1.1 to 9.2.2
2. Install DNN Active Directory 6.01.02
3. At root site on IIS: I turned on Anonymous Authentication and Form Authentication. Configuring Form Authentication loginURL points to DesktopModule/AuthenticationService/ActiveDirectory/Windows Signin.aspx
4. At the folder Active Directory on IIS: I turned off the Anonymous Authentication and turned on Windows Authentication 
5. In the web.config under folder Active Directory I also set Anonymous Authentication is False and set Windows Authentication is True as below:

`<?xml version="1.0" encoding="UTF-8"?>`
`<configuration>`
`    <location path="WindowsSignin.aspx">`
`        <system.web>`
`            <identity password="12345678" userName="Domain\user" />`
`        </system.web>`
`    </location>`
`    <system.webServer>`
`        <security>`
`            <authentication>`
`                <anonymousAuthentication enabled="false" />`
`                <windowsAuthentication enabled="true">`
`                    <providers>`
`                        <clear />`
`                        <add value="NTLM" />`
`                        <add value="Negotiate" />`
`                    </providers>`
`                </windowsAuthentication>`
`            </authentication>`
`        </security>`
`    </system.webServer>`
`</configuration>`

6. I did an IIS reset and accessed to my DNN Site and got the error above.

Any help would be appreciated! 

Thanks
Giang

**Comment by sawest** [comment]
Please summarize your question in one sentence
Give a more extended description
Steps to reproduce (if needed)
Other comments or remarks

**Comment by giangpv171** [comment]
Hi Sawest,

I updated my question. Thank you so much.

Thanks
Giang

**Comment by giangpv171** [comment]
Hi Sawest,

Do the same setting work for DNN 9.1.1 (before upgrade)? Yes, it worked

Does the error go away if Anonymous Authentication is enabled? No, i still persists

I have copied the DNN website of production and rebuild it in UAT. Then I redo all steps I mentioned in the above question. It works fine. 

Thanks
