### ISSUE TITLE
UI options don't do anything

### ISSUE THREAD

**Issue by PodexPefectusSum** [DNNCommunity/DNN.ActiveDirectory#6]
I'm configuring for the first time on Win2k8 R2 with DNN 8.03 or so.  I have two AD OUs, one I want to be able to log into DNN via AD and one I don't (let's call them New York & Buffalo).  So I'm using the root domain:

OU=Buffalo,DC=Domain,DC=com

But DNN doesn't appear to be restricting to this path.

I've also tried checking the "Do Not Automatically Create Users?" checkbox because buffalo only has a handful of users that I'd need to add.

In both cases, users from NY can log in without issue.  DNN just creates an account and everyone can just log right in.

I followed the documentation on codeplex (there doesn't appear to be anything on github and the codeplex documentation looks like it's for DNN 5) which says that when you click "update authentication settings" you should get some feedback about whether it was successful and I don't.

I'm logging in use the DNN form, I've set the site to default to Active Directory and I'm just using the standard login controls.  I'm not using the windowssignin.aspx page because that doesn't work.

**Comment by sawest** [comment]
I am going through old issues.  Firstly, this module is not written to restrict to OUs but to domains only.  This is a feature we can look at adding in the future.

As for the Do Not Automatically Create Users option, please install the latest version and see if that problem is resolved.
