### ISSUE TITLE
A fully functional AD Authentication module for dnn released at dnn store.

### ISSUE THREAD

**Issue by mortezakermani** [DNNCommunity/DNN.ActiveDirectory#61]
To whom it may concern;

A fully functional Active Directory Authentication module for dnn released at dnn store.

This module integrates DNN or Evoq with Windows Active Directory (AD) and LDAP. It allows company employees to login to a DotNetNuke intranet installation using their Windows login credentials and automatically sync their DNN profile and security group and role data.

You can read more about it using [this link](https://store.dnnsoftware.com/home/product-details/active-directory-authentication-v10).

**Comment by valadas** [comment]
@mortezakermani Please avoid marketing proprietary solutions in community channels. We try hard to have some rules regarding community projects. This includes trying to not favor any specific vendor unless it is in the context or answering a user question or something like that.
