### ISSUE TITLE
Does this support Active Directory 2016 and LDAPS?

### ISSUE THREAD

**Issue by smwelch** [DNNCommunity/DNN.ActiveDirectory#68]
Does this support Active Directory 2016 and LDAPS?

**Comment by sawest** [comment]
I am not sure why it would not support AD 2016. I believe we have it running against newer AD than that currently.  I am not familiar with LDAPS nor have I tested this module with LDAPS.  I would say it probably wont work.

**Comment by smwelch** [comment]
Hi Steve,

Does this module or Active Directory use ldap?  If yes, Microsoft is ending support for ldap and requiring ldaps as of March 20th.  If this module does not use/require ldap, then there is no issue.

Thanks,

Scott
