### ISSUE TITLE
Feature request: setting to remove (or hide) Standard login option

### ISSUE THREAD

**Issue by Shane-at-the-Library** [DNNCommunity/DNN.ActiveDirectory#69]
I am running DNN v. 09.05.00 with DNN_ActiveDirectoryAuthentication version 7.0.0. 

I need the ability to display only the Windows Login; like the "Hide Login Controls" except instead of working as that setting does, to hide the Windows Login button, this feature I am requesting is to hide the Standard login button. All of my users sign in with their Windows credentials, and they get confused with having to choose between Standard and Windows Login.

**Comment by sawest** [comment]
The standard button is created by the DNN instance and not by the authentication provider.  To make the standard button go away, you can open the default DNN authentication provider settings in "Extensions" and uncheck the Enabled box.  This will disable the default authentication provider.

Warning!  You must promote one of your Active Directory users to a superuser first!  If you do not, then you will not have any superuser access after you disable the default provider and you will have not way to re-enable it.
