### ISSUE TITLE
Help with version

### ISSUE THREAD

**Issue by masanchezrolatbc** [DNNCommunity/DNN.ActiveDirectory#76]
Hi,

Someone knows which version of visual studio for debug or modify the code?

Help pls =D

**Comment by valadas** [comment]
I have not tried all Visual Studio versions, I use 2019 but I am guessing it probably works on 2015 and up... It's just a guess.

Also, it's not that much about the Visual Studio version as much, you could use VSCode or Ryder and other tooling, what's more important is the build tooling (in this case v12 and the dependencies, in this case .NetFramework 4.5.2 I think).

If you don't have any installed, then I would install 2019 (free edition should be fine).

If you do have something installed and it does not build, then let's go with those error messages and troubleshoot from there...

I am closing this issue, but feel free to comment if you have issues building...
